version: "3"

services:
  app:
    build: .
    image: flashcards:latest
    ports:
      - "80:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: .
    image: flashcards:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: python /app/flaskapp.py
    environment:
      - CHOKIDAR_USEPOLLING=true
